import {
  Folder,
  FolderGit2,
  FolderOpen,
  Rocket,
  Database,
  Code,
  Code2,
  Globe,
  Terminal,
  Box,
  Boxes,
  Layers,
  Server,
  Cpu,
  Cloud,
  Bot,
  Sparkles,
  FlaskConical,
  Palette,
  Wrench,
  BookOpen,
  ShieldCheck,
  Bug,
  Zap,
  Package,
  GitBranch,
  GitFork,
  Smartphone,
  Monitor,
  Gamepad2,
  LineChart,
  Lock,
  Key,
  FileCode,
  Brain,
  Network,
  Workflow,
  Webhook,
  Container,
  HardDrive,
  Pencil,
  PenTool,
  Music,
  Camera,
  Coffee,
  Flame,
  Star,
  Heart,
} from 'lucide-react'
import type { LucideProps } from 'lucide-react'
import type { ComponentType } from 'react'
import { ICON_SIZE, ICON_STROKE } from './Icon'

export const PROJECT_ICONS: Record<string, ComponentType<LucideProps>> = {
  Folder,
  FolderGit2,
  FolderOpen,
  Rocket,
  Database,
  Code,
  Code2,
  Globe,
  Terminal,
  Box,
  Boxes,
  Layers,
  Server,
  Cpu,
  Cloud,
  Bot,
  Sparkles,
  FlaskConical,
  Palette,
  Wrench,
  BookOpen,
  ShieldCheck,
  Bug,
  Zap,
  Package,
  GitBranch,
  GitFork,
  Smartphone,
  Monitor,
  Gamepad2,
  LineChart,
  Lock,
  Key,
  FileCode,
  Brain,
  Network,
  Workflow,
  Webhook,
  Container,
  HardDrive,
  Pencil,
  PenTool,
  Music,
  Camera,
  Coffee,
  Flame,
  Star,
  Heart,
}

export const PROJECT_ICON_NAMES = Object.keys(PROJECT_ICONS)

export const DEFAULT_PROJECT_ICON = 'Folder'

// Renderiza o ícone lucide pelo nome. Fallback (Folder) quando name é null/vazio
// ou não está no set curado — cobre projetos legados cujo icon era um emoji.
export function renderProjectIcon(name: string | null | undefined, props?: LucideProps) {
  const Component = (name && PROJECT_ICONS[name]) || PROJECT_ICONS[DEFAULT_PROJECT_ICON]
  return <Component size={ICON_SIZE} strokeWidth={ICON_STROKE} {...props} />
}
